fix for empty parentheses in ProfileGenericParser
ndokter/dsmr_parser pull request #57
Opened 2020-09-08 13:09 UTC by avandermeer

With an iskra m550 I got the following exception:

```python
Failed to parse telegram: ("Invalid '%s' line for '%s'", '99.97.0()\r\n', <dsmr_parser.parsers.ProfileGenericParser object at 0x76814210>)
```

This is caused by empty parentheses `()`. 

This fixes the issue for me: 

* make sure the `_is_line_wellformed` function returns true if there are empty parentheses; 
* if  `_is_line_wellformed`  returns `true`, the empty value will be turned into `None`
* since ` _parse_values` can't handle None values, I also added a check in `_parse_values`  ; if `None` is the case, call the parent function

2020-11-03 20:42 UTC, ndokter commented
Sorry for my late response. Do you happen to have an example telegram in which this occurs?

2020-11-03 21:16 UTC, avandermeer commented
```
>>> line = ser.readline()
>>> line
b'/ISK5\\2M550E-1011\r\n'
>>> ser.readline()
b'\r\n'
>>> ser.readline()
b'1-3:0.2.8(50)\r\n'
>>> ser.readline()
b'0-0:1.0.0(200903170157S)\r\n'
>>> ser.readline()
b'0-0:96.1.1(4530303333303036383530363530383137)\r\n'
>>> ser.readline()
b'1-0:1.8.1(001111.528*kWh)\r\n'
>>> ser.readline()
b'1-0:1.8.2(001111.645*kWh)\r\n'
>>> ser.readline()
b'1-0:2.8.1(000111.103*kWh)\r\n'
>>> ser.readline()
b'1-0:2.8.2(001111.969*kWh)\r\n'
>>> ser.readline()
b'0-0:96.14.0(0002)\r\n'
>>> ser.readline()
b'1-0:1.7.0(00.044*kW)\r\n'
>>> ser.readline()
b'1-0:2.7.0(00.000*kW)\r\n'
>>> ser.readline()
b'0-0:96.7.21(00011)\r\n'
>>> ser.readline()
b'0-0:96.7.9(00002)\r\n'
>>> ser.readline()
b'1-0:99.97.0()\r\n'
>>> ser.readline()
b'1-0:32.32.0(00007)\r\n'
>>> ser.readline()
b'1-0:32.36.0(00001)\r\n'
>>> ser.readline()
b'0-0:96.13.0()\r\n'
>>> ser.readline()
b'1-0:32.7.0(236.9*V)\r\n'
>>> ser.readline()
b'1-0:31.7.0(001*A)\r\n'
>>> ser.readline()
b'1-0:21.7.0(00.044*kW)\r\n'
>>> ser.readline()
b'1-0:22.7.0(00.000*kW)\r\n'
>>> ser.readline()
b'0-1:24.1.0(003)\r\n'
>>> ser.readline()
b'0-1:96.1.0(4730303332353635353432373531353137)\r\n'
>>> ser.readline()
b'0-1:24.2.1(200903170004S)(01111.003*m3)\r\n'
>>> ser.readline()
b'!6438\r\n'
```

2020-11-21 20:53 UTC, lowdef requested changes
hi, the following code shows that the current proposal will break things. The reason is that an ill formed ProfileGenericObject is created.

```python
from dsmr_parser.parsers import ProfileGenericParser
from dsmr_parser.profile_generic_specifications import BUFFER_TYPES, PG_HEAD_PARSERS, PG_UNIDENTIFIED_BUFFERTYPE_PARSERS

pef_parser = ProfileGenericParser(BUFFER_TYPES, PG_HEAD_PARSERS, PG_UNIDENTIFIED_BUFFERTYPE_PARSERS)

pef_string1 = r"1-0:99.97.0(2)(0-0:96.7.19)(160517193108S)(0000002976*s)(160516081657S)(0000005299*s)\r\n"
pef_out1 = pef_parser.parse(pef_string1)

po = pef_out1
try:
    print("buffer_type : {}".format(po.buffer_type))
except:
    print("buffer_type : BREAKS!!!!")
print("buffer_length : {}".format(po.buffer_length))
try:
    print("buffer : {}".format(po.buffer))
except:
    print("buffer : BREAKS!!!!")
print("values : {}".format(po.values))
try:
    print("PEFObject : {}".format(po))
except:
    print("buffer : BREAKS!!!!")
try:
    print("json : {}".format(po.to_json()))
except:
    print("json : BREAKS!!!!")

pef_string2 = r'1-0:99.97.0()\r\n'
pef_out2 = pef_parser.parse(pef_string2)

po = pef_out2
try:
    print("buffer_type : {}".format(po.buffer_type))
except:
    print("buffer_type : BREAKS!!!!")
print("buffer_length : {}".format(po.buffer_length))
try:
    print("buffer : {}".format(po.buffer))
except:
    print("buffer : BREAKS!!!!")
print("values : {}".format(po.values))
try:
    print("PEFObject : {}".format(po))
except:
    print("buffer : BREAKS!!!!")
try:
    print("json : {}".format(po.to_json()))
except:
    print("json : BREAKS!!!!")

```
Following output is generated:
```
buffer_type : 0-0:96.7.19
buffer_length : 2
buffer : [<dsmr_parser.objects.MBusObject object at 0x7fd3237d9d00>, <dsmr_parser.objects.MBusObject object at 0x7fd3237dceb0>]
values : [{'value': 2, 'unit': None}, {'value': '0-0:96.7.19', 'unit': None}, {'value': datetime.datetime(2016, 5, 17, 17, 31, 8, tzinfo=<UTC>), 'unit': None}, {'value': 2976, 'unit': 's'}, {'value': datetime.datetime(2016, 5, 16, 6, 16, 57, tzinfo=<UTC>), 'unit': None}, {'value': 5299, 'unit': 's'}]
PEFObject : 	 buffer length: 2
	 buffer type: 0-0:96.7.19
	 event occured at: 2016-05-17T19:31:08+02:00	 for: 2976 [s]
	 event occured at: 2016-05-16T08:16:57+02:00	 for: 5299 [s]
json : {"buffer_length": 2, "buffer_type": "0-0:96.7.19", "buffer": [{"datetime": "2016-05-17T19:31:08+02:00", "value": 2976, "unit": "s"}, {"datetime": "2016-05-16T08:16:57+02:00", "value": 5299, "unit": "s"}]}
buffer_type : BREAKS!!!!
buffer_length : None
buffer : BREAKS!!!!
values : [{'value': None, 'unit': None}]
buffer : BREAKS!!!!
json : BREAKS!!!!
```

I suggest you rewrite, such that created GenericParserObject has valid entries and does not break. I think what would work is if the following values are returned for this special case:

```
buffer_type : None
buffer_length : 0
buffer : []
values : []
```

2020-12-14 15:55 UTC, ndokter approved these changes

2020-12-14 15:55 UTC, merged

2020-12-15 14:07 UTC, ndokter commented
Thank you @lowdef. I've reverted this change for now. Feel free to reopen